"use strict";

var SET_ARRAY = [{
  "name": "~",
  "cubes": [19, 7, 12, 4, 20, 8, 9, 3, 17, 10, 5, 2, 11, 18, 6, 15, 16, 14, 13, 22, 21, 24, 1, 23]
}];
var CUBES = [{
  "no": 19,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 10,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 7,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 10,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 12,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 3,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 4,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 3,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 20,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 6,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 8,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 11,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 9,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 4,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 3,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 2,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 17,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 2,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 10,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 11,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 5,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 8,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 2,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 1,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 11,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 7,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 18,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 7,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 6,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 9,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 15,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 6,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 16,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 9,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 14,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 1,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 13,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 5,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 22,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 4,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 21,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 8,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 24,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 5,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 1,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 0,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 23,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 0,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}];