"use strict";

var SET_ARRAY = [{
  "name": "NO-1",
  "cubes": [12175, 5455, 19608, 19066, 18586]
}];
var CUBES = [{
  "no": 12175,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 3,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "0234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 5455,
  "actCells": [{
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 4,
    "relation": 0,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 10,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 3,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "3"
}, {
  "no": 19608,
  "actCells": [{
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 3
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": ""
}, {
  "no": 19066,
  "actCells": [{
    "layerIndex": 2,
    "relation": 3,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 8,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 3
  }, {
    "layerIndex": 3,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 1
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": "0"
}, {
  "no": 18586,
  "actCells": [{
    "layerIndex": 2,
    "relation": 3,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 8,
    "rowIndex": 0,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 1,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 1
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 0,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 3
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 0,
    "colIndex": 4
  }, {
    "layerIndex": 2,
    "relation": 3,
    "feature": 3,
    "sixFace": 0,
    "faceDirection": 0,
    "twelveEdge": 5,
    "rowIndex": 1,
    "colIndex": 0
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 3,
    "faceDirection": 3,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 1
  }, {
    "layerIndex": 2,
    "relation": 0,
    "feature": 2,
    "sixFace": 4,
    "faceDirection": 2,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 2
  }, {
    "layerIndex": 1,
    "relation": 0,
    "feature": 2,
    "sixFace": 2,
    "faceDirection": 1,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 3
  }, {
    "layerIndex": 4,
    "relation": 0,
    "feature": 2,
    "sixFace": 5,
    "faceDirection": 0,
    "twelveEdge": 12,
    "rowIndex": 1,
    "colIndex": 4
  }],
  "gridLines": [{
    "xStart": 0,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 0,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 1,
    "lineStyle": 3
  }, {
    "xStart": 0,
    "xEnd": 1,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 2,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 2,
    "xEnd": 3,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 3,
    "xEnd": 4,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 4,
    "xEnd": 5,
    "yStart": 2,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 0,
    "yEnd": 1,
    "lineStyle": 4
  }, {
    "xStart": 0,
    "xEnd": 0,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }, {
    "xStart": 1,
    "xEnd": 1,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 2,
    "xEnd": 2,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 3,
    "xEnd": 3,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 4,
    "xEnd": 4,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 2
  }, {
    "xStart": 5,
    "xEnd": 5,
    "yStart": 1,
    "yEnd": 2,
    "lineStyle": 4
  }],
  "rowCount": 2,
  "colCount": 5,
  "firstRowActCellColIndexBill": "01234",
  "lastRowEmptyCellColIndexBill": ""
}];